dependencies:
  - scipy==1.7.3
  - numpy==1.21.5
  - pip==20.2.4
  - pip:
      # environment dependencies
      - aenum==3.1.5
      - networkx==2.6.3
      - triangle==20200424
      - Polygon3==3.0.9.1
      - pybind11==2.9.0
      - wandb==0.12.17
      - patchelf==0.15.0.0
      # learning dependencies
      - gym==0.21.0
      # CommonRoad packages
      - commonroad-io==2022.1
      - commonroad-vehicle-models
      - commonroad-route-planner==2022.1
      - commonroad-drivability-checker==2021.4.1
      # Evaluation dependencies
      - SALib==1.3.13
      # for inverse constraint RL
      - tqdm
      - mpl-scatter-density
      - pickle5