task: 'GAIL-highD-velocity-distance'
group: 'GAIL'
device: 'cuda'
verbose: 2
env:
  config_path: "../config/highD_velocity_distance_constraint/highD_environment_configurations_no_velocity-40_distance-20_penalty.yaml"
  train_env_id : 'commonroad-v1'
  eval_env_id: 'commonroad-v1'
  save_dir: '../save_model'
  cost_info_str: 'cost'
  use_cost: True
  reward_gamma: 0.99
  cost_gamma: 0.99
  dont_normalize_obs: False
  dont_normalize_reward: False
  dont_normalize_cost: False  # no cost
  record_info_names: ["ego_velocity_x", "ego_velocity_y", "same_lane_leading_obstacle_distance"]
  record_info_input_dims: [ 6, 7, 22] # the dim of record info in inputs=(obs, action)
  visualize_info_ranges: [ [ 20, 50 ], [ -10, 10 ], [ 0, 100 ] ]

running:
  save_every: 500000
  eval_every: 200000
  expert_rollouts: 100
  expert_path: '../data/expert_data/HighDVelocityDistanceConstraint'

PPO:
  policy_name: 'MlpPolicy'
  learning_rate: 0.0003
  n_steps: 2048
  n_epochs: 10
  reward_gamma: 0.99
  reward_gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  reward_vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1
  target_kl: 0.01
  shared_layers: null
  policy_layers: [64, 64]
  reward_vf_layers: [64, 64]
  batch_size: null  # 64
#  eval_every: 2048
  timesteps: 2500000

DISC:
  disc_batch_size: null
  disc_eps: 1e-05
  disc_layers: [ 30 ]
  disc_learning_rate: 0.003
  disc_normalize": false
  disc_obs_select_dim: null
  disc_acs_select_dim: null  # null means all
  disc_plot_every: 1
  clip_obs: 20
  num_spurious_features: null
  freeze_gail_weights: false
  use_cost_net: false
  learn_cost: true
  gail_path: null
  use_cost_shaping_callback: false