map_height: 7
map_width: 7
n_actions: 8
transition_prob: 1
reward_states: [[6, 6]]
terminal_states: [[6, 6]]
unsafe_states: [[1,1], [2,1], [3,1], [4,1], [5,1],
                [1,2], [2,2], [3,2], [4,2], [5,2],
                [1,3], [2,3], [3,3], [4,3], [5,3],
                [1,4], [2,4], [3,4], [4,4], [5,4],
                [1,5], [2,5], [3,5], [4,5], [5,5]]
start_states: [[0,0]]
