map_height: 7
map_width: 7
n_actions: 8
transition_prob: 1
reward_states: [[6, 6]]
terminal_states: [[6, 6]]
unsafe_states: [[2,0], [2,1], [2,2], [2,3], [2,4], [4,2], [4,3], [4,4], [4,5], [4,6]]
start_states: [[0,0]]
